spring:
  datasource:
    url: jdbc:h2:mem:alpha
    username: sa
    password:
  batch:
    job:
      enabled: false      
      
  servlet: 
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
      

app:
  file-store-location: /home/narayana/Desktop/batch-files/
  
